#!/bin/bash
# TechDaily GitHub Pages 部署脚本
# 将报告自动推送到 GitHub Pages，实现外部可访问

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# 配置
GITHUB_USER="${GITHUB_USER:-}"
GITHUB_REPO="${GITHUB_REPO:-tech-daily-reports}"
BRANCH="gh-pages"

if [ -z "$GITHUB_USER" ]; then
    echo "错误: 请设置 GITHUB_USER 环境变量"
    echo "示例: export GITHUB_USER=your-username"
    exit 1
fi

REPO_URL="https://github.com/${GITHUB_USER}/${GITHUB_REPO}.git"

echo "=========================================="
echo "TechDaily GitHub Pages 部署"
echo "=========================================="
echo "仓库: ${REPO_URL}"
echo ""

# 创建临时部署目录
DEPLOY_DIR="/tmp/tech-daily-deploy"
rm -rf "$DEPLOY_DIR"
mkdir -p "$DEPLOY_DIR"

# 复制报告文件
cp output/*.html "$DEPLOY_DIR/" 2>/dev/null || true
cp output/*.md "$DEPLOY_DIR/" 2>/dev/null || true
cp -r output/*.html "$DEPLOY_DIR/" 2>/dev/null || true

# 创建索引页
cat > "$DEPLOY_DIR/index.html" << 'HTMLEOF'
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>TechDaily Reports</title>
    <style>
        body { font-family: -apple-system, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; }
        h1 { color: #333; }
        .report-list { list-style: none; padding: 0; }
        .report-list li { margin: 10px 0; padding: 15px; background: #f5f5f5; border-radius: 8px; }
        .report-list a { color: #0366d6; text-decoration: none; font-size: 1.1em; }
        .report-list a:hover { text-decoration: underline; }
        .meta { color: #666; font-size: 0.9em; margin-top: 5px; }
    </style>
</head>
<body>
    <h1>TechDaily 科技资讯日报</h1>
    <p>自动生成科技资讯日报归档</p>
    <ul class="report-list">
HTMLEOF

# 列出报告文件
for file in "$DEPLOY_DIR"/tech-daily-*.html; do
    if [ -f "$file" ]; then
        filename=$(basename "$file")
        date_str=$(echo "$filename" | grep -oP 'tech-daily-\K[0-9]{4}-[0-9]{2}-[0-9]{2}' || echo "unknown")
        cat >> "$DEPLOY_DIR/index.html" << EOF
        <li>
            <a href="${filename}">${date_str} 日报</a>
            <div class="meta">${filename}</div>
        </li>
EOF
    fi
done

cat >> "$DEPLOY_DIR/index.html" << 'HTMLEOF'
    </ul>
    <hr>
    <p style="color: #999; font-size: 0.9em;">Generated by TechDaily</p>
</body>
</html>
HTMLEOF

# 初始化 git 并推送
cd "$DEPLOY_DIR"
git init
git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH"
git add .
git commit -m "Deploy reports $(date '+%Y-%m-%d %H:%M:%S')"

# 推送到 GitHub（需要配置 token 或 SSH）
if git remote | grep -q origin; then
    git remote set-url origin "$REPO_URL"
else
    git remote add origin "$REPO_URL"
fi

echo "推送到 GitHub..."
git push -u origin "$BRANCH" --force

echo ""
echo "=========================================="
echo "部署完成!"
echo "访问地址: https://${GITHUB_USER}.github.io/${GITHUB_REPO}/"
echo "最新报告: https://${GITHUB_USER}.github.io/${GITHUB_REPO}/latest.html"
echo "=========================================="

# 清理
rm -rf "$DEPLOY_DIR"
